networks:
  homeserver:
    external: true
    name: homeserver

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      DOMAIN: https://vaultwarden.amr-cloud.tail80ea1b.ts.net
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
    networks:
      - homeserver