networks:
  homeserver:
    external: true
    name: homeserver

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DOMAIN: https://${DOMAIN}/vault
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - ${DATA_PATH}/vaultwarden:/data
    networks:
      - homeserver