services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    restart: unless-stopped
    hostname: home
    network_mode: host
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"
      TS_IP_FORWARDING: "1"
      TS_EXTRA_ARGS: --advertise-routes=${HOMESERVER_SUBNET} --accept-routes
    volumes:
      - ${DATA_PATH}/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE