networks:
  homeserver:
    external: true
    name: homeserver

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich
    restart: unless-stopped
    depends_on:
      - immich-redis
      - immich-postgres
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE}
      REDIS_HOSTNAME: immich-redis
    volumes:
      - ${DATA_PATH}/immich/upload:/usr/src/app/upload
    networks:
      - homeserver

  immich-redis:
    image: valkey/valkey:9-alpine
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - homeserver

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_DB: ${IMMICH_DB_DATABASE}
    volumes:
      - ${DATA_PATH}/immich/db:/var/lib/postgresql/data
    networks:
      - homeserver