networks:
  homeserver:
    external: true
    name: homeserver

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/jellyfin/config:/config
      - ${DATA_PATH}/media:/media
    networks:
      homeserver:
        ipv4_address: ${JELLYFIN_IP}